// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	{{- range $path,$_ :=  .Imports}}
	"{{- $path }}"
	{{- end }}
	"{{ .RootDir }}/internal/svc"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
   {{- range $prefixMiddleware,$value := .Routes}}
       {{- if $value.HasMiddleware }}
       server.AddRoutes(
          rest.WithMiddlewares(
              []rest.Middleware{ {{ $value.Middleware }} },
              []rest.Route{
                  {{ range $value.Routes}}
                  {
                      Method:  {{ .Method }},
                      Path:    "{{ .Path }}",
                      Handler: {{ .Handler }}(serverCtx),
                  },
                  {{ end }}
              }...,
          ),
          rest.WithPrefix("{{$value.Prefix}}"),
       )
       {{- else }}
       server.AddRoutes(
           []rest.Route{
               {{- range $value.Routes}}
               {
                   Method:  {{ .Method }},
                   Path:    "{{ .Path }}",
                   Handler: {{ .Handler }}(serverCtx),
               },
               {{- end }}
           },
           rest.WithPrefix("{{$value.Prefix}}"),
        )
       {{- end }}
	{{- end }}
}
